# Generated by Django 6.0.6 on 2026-06-21 18:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=20)),
                ('cantidad_lotes', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('costo_estimado', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('precio_venta_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('precio_venta_total', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to=settings.AUTH_USER_MODEL)),
                ('receta_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='recipes.recetaversion')),
            ],
            options={
                'db_table': 'production_ordenproduccion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'estado'], name='production__owner_i_9eec6e_idx'), models.Index(fields=['owner', 'fecha_programada'], name='production__owner_i_bd9be5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('owner', 'codigo'), name='production_orden_codigo_owner_uniq'), models.CheckConstraint(condition=models.Q(('cantidad_lotes__gt', 0)), name='production_orden_lotes_positivos')],
            },
        ),
    ]
