# Generated by Django 6.0.6 on 2026-06-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('L', 'Leído')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leido_at', models.DateTimeField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'db_table': 'public_site_mensajecontacto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='public_site_estado_c1f4c5_idx'), models.Index(fields=['-created_at'], name='public_site_created_a2472f_idx')],
            },
        ),
    ]
