# Generated by Django 6.0.6 on 2026-06-20 18:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_monedas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(blank=True, default='', max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('unidad_peso_default', models.CharField(default='g', max_length=10)),
                ('unidad_volumen_default', models.CharField(default='ml', max_length=10)),
                ('unidad_conteo_default', models.CharField(default='unidad', max_length=10)),
                ('margen_objetivo_pct', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('user_type', models.CharField(choices=[('M', 'Master'), ('U', 'User')], default='U', max_length=1)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email_confirm_code', models.CharField(blank=True, max_length=6, null=True)),
                ('email_confirm_exp', models.DateTimeField(blank=True, null=True)),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('tfa_verified', models.BooleanField(default=False)),
                ('last_totp_reset', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moneda', models.ForeignKey(default='COP', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='core.moneda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'db_table': 'accounts_userprofile',
            },
        ),
    ]
