[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn config.wsgi:application -c gunicorn.conf.py"
preDeployCommand = "python manage.py migrate --noinput"
restartPolicyType = "ON_FAILURE"
