# Generated by Django 6.0.6 on 2026-06-20 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_monedas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('banco', 'Banco'), ('transferencia', 'Transferencia'), ('pagomovil', 'Pago móvil'), ('efectivo', 'Efectivo'), ('otros', 'Otros')], default='', max_length=20)),
                ('payment_voucher', models.CharField(blank=True, default='', max_length=50)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modalidad', models.CharField(choices=[('M', 'Mensual'), ('A', 'Anual')], default='M', max_length=1)),
                ('other_data', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('suspendido', 'Suspendido'), ('consumido', 'Consumido')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_controls_created', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_controls', to='core.moneda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_controls', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_controls_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de pago',
                'verbose_name_plural': 'Controles de pago',
                'db_table': 'billing_paymentcontrol',
                'ordering': ['-payment_date', '-start_date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'estado'], name='billing_pay_owner_i_462cd8_idx')],
            },
        ),
    ]
