# Generated by Django 6.0.6 on 2026-06-20 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcontrol',
            name='plazo_de_gracia',
            field=models.PositiveSmallIntegerField(db_column='plazoDeGracia', default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Plazo de gracia (días)'),
        ),
    ]
