# Generated by Django 6.0.6 on 2026-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('simbolo', models.CharField(max_length=10)),
                ('decimales', models.PositiveSmallIntegerField(default=2)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'core_moneda',
                'ordering': ['orden', 'codigo'],
            },
        ),
    ]
