# Generated by Django 6.0.6 on 2026-06-20 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(choices=[('G', 'Global'), ('P', 'Personal')], default='G', max_length=1)),
                ('tipo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
                ('resumen', models.CharField(blank=True, default='', max_length=300)),
                ('fecha_noticia', models.DateField()),
                ('visible_desde', models.DateField()),
                ('visible_hasta', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('destacada', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('enlace_interno', models.CharField(blank=True, default='', max_length=200)),
                ('enlace_externo', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias_creadas', to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='noticias_personales', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='noticias_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'noticias_noticia',
                'ordering': ['-destacada', '-fecha_noticia', 'orden'],
                'indexes': [models.Index(fields=['status', 'visible_desde', 'visible_hasta'], name='noticias_no_status_b38040_idx'), models.Index(fields=['alcance', 'fecha_noticia'], name='noticias_no_alcance_85e701_idx')],
            },
        ),
    ]
