# Generated by Django 6.0.6 on 2026-06-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='detalle',
            field=models.TextField(blank=True, default=''),
        ),
    ]
