# Generated by Django 6.0.6 on 2026-06-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta_nombre', models.CharField(max_length=100)),
                ('receta_version_numero', models.PositiveIntegerField()),
                ('rendimiento_cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rendimiento_unidad', models.CharField(max_length=30)),
                ('costo_ingredientes', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_indirectos', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_version_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_version_por_porcion', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_lotes', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidades_producidas', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo_produccion_total', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo_produccion_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('margen_objetivo_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta_sugerido_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('precio_venta_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ganancia_estimada', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ganancia_real', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('margen_real_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('diferencia_costo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('perdida', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('moneda_codigo', models.CharField(max_length=3)),
                ('orden_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('periodo_anio', models.PositiveSmallIntegerField()),
                ('periodo_mes', models.PositiveSmallIntegerField()),
                ('fecha_produccion', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_produccionanalytics',
                'ordering': ['-fecha_produccion'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionAnalyticsProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=150)),
                ('producto_categoria', models.CharField(max_length=50)),
                ('cantidad_normalizada_total', models.DecimalField(decimal_places=6, max_digits=14)),
                ('unidad_base', models.CharField(max_length=10)),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo_linea_total', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
            options={
                'db_table': 'analytics_produccionanalyticsproducto',
            },
        ),
    ]
