# Generated by Django 6.0.6 on 2026-06-21 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0001_initial'),
        ('production', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionanalytics',
            name='orden_produccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='analytics', to='production.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='produccionanalytics',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produccion_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produccionanalytics',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produccion_analytics', to='recipes.receta'),
        ),
        migrations.AddField(
            model_name='produccionanalytics',
            name='receta_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produccion_analytics', to='recipes.recetaversion'),
        ),
        migrations.AddField(
            model_name='produccionanalyticsproducto',
            name='analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_producto', to='analytics.produccionanalytics'),
        ),
        migrations.AddField(
            model_name='produccionanalyticsproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_uso', to='catalog.producto'),
        ),
        migrations.AddIndex(
            model_name='produccionanalytics',
            index=models.Index(fields=['owner', 'periodo_anio', 'periodo_mes'], name='analytics_p_owner_i_8953d0_idx'),
        ),
        migrations.AddIndex(
            model_name='produccionanalytics',
            index=models.Index(fields=['owner', 'receta'], name='analytics_p_owner_i_191a30_idx'),
        ),
        migrations.AddIndex(
            model_name='produccionanalytics',
            index=models.Index(fields=['owner', 'receta_version'], name='analytics_p_owner_i_47f36f_idx'),
        ),
        migrations.AddIndex(
            model_name='produccionanalyticsproducto',
            index=models.Index(fields=['analytics', 'producto'], name='analytics_p_analyti_1010e0_idx'),
        ),
    ]
