# Generated by Django 6.0.6 on 2026-06-20 19:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, default='', max_length=30)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('status', models.CharField(choices=[('P', 'En proceso'), ('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_productcategory',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('unidad_base', models.CharField(max_length=20)),
                ('costo_por_unidad_base', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('P', 'En proceso'), ('A', 'Activo'), ('I', 'Inactivo')], default='P', max_length=1)),
                ('proveedor', models.CharField(blank=True, default='', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalog.productcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConversionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=50)),
                ('desde_unidad', models.CharField(max_length=20)),
                ('hacia_unidad', models.CharField(max_length=20)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_unidad', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_unidad', to='catalog.producto')),
            ],
            options={
                'db_table': 'catalog_conversionunidad',
                'ordering': ['desde_unidad', 'hacia_unidad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CostoIndirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidad_cobro', models.CharField(choices=[('hora', 'Hora'), ('minuto', 'Minuto'), ('lote', 'Lote'), ('porcion', 'Porcion'), ('mes', 'Mes'), ('fijo', 'Fijo')], default='hora', max_length=15)),
                ('costo_por_unidad', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('P', 'En proceso'), ('A', 'Activo'), ('I', 'Inactivo')], default='P', max_length=1)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_indirectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_costoindirecto',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['owner', 'status'], name='catalog_cos_owner_i_6d2761_idx'), models.Index(fields=['owner', 'unidad_cobro'], name='catalog_cos_owner_i_fea662_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('costo_por_unidad__gte', 0)), name='catalog_costoindirecto_costo_no_negativo')],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['owner', 'status'], name='catalog_pro_owner_i_524595_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('owner', 'nombre'), name='catalog_productcategory_owner_nombre_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo__gt', '')), fields=('owner', 'codigo'), name='catalog_productcategory_owner_codigo_uniq'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['owner', 'status'], name='catalog_pro_owner_i_a44a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['owner', 'categoria'], name='catalog_pro_owner_i_fe7dea_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['owner', 'nombre'], name='catalog_pro_owner_i_6895d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('costo_por_unidad_base__gte', 0)), name='catalog_producto_costo_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='conversionunidad',
            index=models.Index(fields=['owner', 'producto'], name='catalog_con_owner_i_9aa40d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionunidad',
            index=models.Index(fields=['owner', 'desde_unidad', 'hacia_unidad'], name='catalog_con_owner_i_55bc60_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversionunidad',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='catalog_conversionunidad_factor_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='conversionunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('producto__isnull', False)), fields=('owner', 'producto', 'desde_unidad'), name='catalog_conversionunidad_owner_producto_desde_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conversionunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('producto__isnull', True)), fields=('owner', 'desde_unidad', 'hacia_unidad'), name='catalog_conversionunidad_owner_desde_hacia_generic_uniq'),
        ),
    ]
