# Generated by Django 6.0.6 on 2026-06-21 16:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_corta', models.CharField(blank=True, default='', max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('status', models.CharField(choices=[('P', 'En proceso'), ('A', 'Activo'), ('I', 'Inactivo')], default='P', max_length=1)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes_receta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('notas_cambio', models.TextField(blank=True, default='')),
                ('rendimiento_cantidad', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('rendimiento_unidad', models.CharField(default='porciones', max_length=30)),
                ('costo_ingredientes', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('costo_indirectos', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('costo_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('costo_por_porcion', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('margen_aplicado_pct', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='recipes.receta')),
            ],
            options={
                'db_table': 'recipes_recetaversion',
                'ordering': ['receta_id', '-numero_version'],
            },
        ),
        migrations.CreateModel(
            name='RecetaPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('instruccion', models.TextField()),
                ('tiempo_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='recipes.recetaversion')),
            ],
            options={
                'db_table': 'recipes_recetapaso',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.CharField(blank=True, default='', max_length=100)),
                ('cantidad_normalizada', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('costo_linea', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_receta', to='catalog.producto')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='recipes.recetaversion')),
            ],
            options={
                'db_table': 'recipes_recetaingrediente',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecetaCostoIndirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo_linea', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.CharField(blank=True, default='', max_length=100)),
                ('costo_indirecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_receta', to='catalog.costoindirecto')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_indirectos', to='recipes.recetaversion')),
            ],
            options={
                'db_table': 'recipes_recetacostoindirecto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='version_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recetaversion'),
        ),
        migrations.AddConstraint(
            model_name='recetaversion',
            constraint=models.UniqueConstraint(fields=('receta', 'numero_version'), name='recipes_recetaversion_receta_numero_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recetaversion',
            constraint=models.CheckConstraint(condition=models.Q(('rendimiento_cantidad__gt', 0)), name='recipes_recetaversion_rendimiento_positivo'),
        ),
        migrations.AddConstraint(
            model_name='recetapaso',
            constraint=models.UniqueConstraint(fields=('version', 'orden'), name='recipes_recetapaso_version_orden_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recetaingrediente',
            constraint=models.UniqueConstraint(fields=('version', 'producto'), name='recipes_recetaingrediente_version_producto_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recetaingrediente',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='recipes_recetaingrediente_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='recetacostoindirecto',
            constraint=models.UniqueConstraint(fields=('version', 'costo_indirecto'), name='recipes_recetacostoindirecto_version_gasto_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recetacostoindirecto',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='recipes_recetacostoindirecto_cantidad_no_negativa'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['owner', 'status'], name='recipes_rec_owner_i_bb709d_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['owner', 'nombre'], name='recipes_rec_owner_i_4e8914_idx'),
        ),
    ]
